name: sakila-dev
services:
  mariadb:
    image: mariadb:11.4
    container_name: sakila-mariadb
    restart: unless-stopped
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/sakila:/sakila-ro:ro
      - ./db/conf.d/zz-sakila.cnf:/etc/mysql/conf.d/zz-sakila.cnf:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - sakila_net


  adminer:
    image: adminer:latest
    container_name: sakila_adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - sakila_net

networks:
  sakila_net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local

