name: Publish server image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '.github/workflows/publish.yml'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/chrishorler/sakila-server:latest
            ghcr.io/chrishorler/sakila-server:${{ github.sha }}
          provenance: false
